"""Contract layer: todos los modelos Pydantic del sistema.

Nada en la aplicación debe usar dicts libres. Si un dato cruza una frontera
(tool → agent, agent → API, DB → agent), pasa tipado por uno de estos modelos.
"""

from schemas.agent_io import (
    AgenteDestino,
    AgentResponse,
    EventsResponse,
    IntentClass,
    InventoryResponse,
    OrderResponse,
    RouterOutput,
    SessionRequest,
    SommelierResponse,
    SupportResponse,
)
from schemas.api import (
    ApproveRequest,
    ChatRequest,
    MetricasKPI,
    MPWebhookPayload,
    WhatsAppInbound,
)
from schemas.audit import (
    AuditCategoria,
    AuditFinding,
    AuditReport,
    AuditRequest,
    AuditSeverity,
    AuditSummary,
    RunAuditable,
    RunsAuditablesResponse,
    ToolCallRecord,
)
from schemas.customer_profile import (
    CustomerProfile,
    PerfilClienteTipo,
    PreferenciaRegistrada,
    SegmentoCliente,
)
from schemas.evaluation import AdversarialExample, AttackType, GoldenExample
from schemas.judge_rubric import (
    CriterioEvaluacion,
    JudgeCriterioScore,
    JudgeEvaluationResult,
)
from schemas.knowledge_fragment import (
    CapaConocimiento,
    FuenteConocimiento,
    JerarquiaFuente,
    KnowledgeFragment,
)
from schemas.order import (
    CalculatedOrder,
    ConfirmedOrder,
    EstadoOrden,
    LineaPedidoSolicitud,
    Order,
    OrderEstado,
    OrderLine,
    OrderLineItem,
    OrderStatusResponse,
    TipoEntrega,
)
from schemas.session_state import SessionState
from schemas.tool_responses import (
    CalculatedOrderResponse,
    CalculationResponse,
    CreateOrderResponse,
    CustomerContextResponse,
    DeliveryZoneResponse,
    EventoItem,
    EventReservationResponse,
    EventsListResponse,
    FAQResponse,
    PairingResponse,
    PaymentLinkResponse,
    PriceResponse,
    RAGResult,
    ResultadoTool,
    SavePreferenceResponse,
    StockResponse,
    VerifyStockResponse,
    VintageComparisonResponse,
    VintageItem,
)
from schemas.wine_catalog import StockInfo, Varietal, WineProduct

__all__ = [
    "AgentResponse",
    "AdversarialExample",
    "AgenteDestino",
    "ApproveRequest",
    "AttackType",
    "AuditCategoria",
    "AuditFinding",
    "AuditReport",
    "AuditRequest",
    "AuditSeverity",
    "AuditSummary",
    "CalculatedOrder",
    "CalculatedOrderResponse",
    "CalculationResponse",
    "CapaConocimiento",
    "ChatRequest",
    "ConfirmedOrder",
    "CreateOrderResponse",
    "CustomerContextResponse",
    "CriterioEvaluacion",
    "CustomerProfile",
    "DeliveryZoneResponse",
    "EstadoOrden",
    "EventoItem",
    "EventReservationResponse",
    "EventsListResponse",
    "EventsResponse",
    "FAQResponse",
    "FuenteConocimiento",
    "GoldenExample",
    "IntentClass",
    "InventoryResponse",
    "JerarquiaFuente",
    "JudgeCriterioScore",
    "JudgeEvaluationResult",
    "KnowledgeFragment",
    "LineaPedidoSolicitud",
    "MetricasKPI",
    "MPWebhookPayload",
    "Order",
    "OrderEstado",
    "OrderLine",
    "OrderLineItem",
    "OrderResponse",
    "OrderStatusResponse",
    "PairingResponse",
    "PaymentLinkResponse",
    "PerfilClienteTipo",
    "PriceResponse",
    "RAGResult",
    "ResultadoTool",
    "SavePreferenceResponse",
    "PreferenciaRegistrada",
    "RouterOutput",
    "RunAuditable",
    "RunsAuditablesResponse",
    "SegmentoCliente",
    "SessionRequest",
    "SessionState",
    "SommelierResponse",
    "StockInfo",
    "StockResponse",
    "SupportResponse",
    "TipoEntrega",
    "ToolCallRecord",
    "Varietal",
    "VerifyStockResponse",
    "VintageComparisonResponse",
    "VintageItem",
    "WhatsAppInbound",
    "WineProduct",
]
